name: build-and-deploy-parallel-workflow

on:
  push:
    branches:
      - master

jobs:
  install-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3

      - name: Step2 - Install dependencies
        run: npm ci
  
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3
      
      - name: Step2 - Install dependencies
        run: npm ci

      - name: Step3 - Lint
        run: npm run lint

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3

      - name: Step2 - Install dependencies
        run: npm ci

      - name: Step3 - Lint
        run: npm run lint

      - name: Step4 - Test
        run: npm test


  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Checkout code
        uses: actions/checkout@v3

      - name: Step2 - Install dependencies
        run: npm ci

      - name: Step3 - Build
        run: npm run build

      - name: Step4 - Deploy
        run: echo "Deploying application..."