name: manual-workflow

on:
  workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step1 - Runs a 1 line script
        run: echo Hello, world!

      - name: Step2 - Runs a multi line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Step3 - Runs a script which uses expression and prints github context
        run: echo ${{ toJSON(github) }}
